### PR TITLE
mark module as deprecated

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by atgeirr** [comment]
Should we also remove the contents of the repository just to guard against possible messing up by users?

**Comment by akva2** [comment]
We did not to that for porsol or polymer but if you think it better i see no reason not to as such.

**Comment by atgeirr** [comment]
There were no problems with this connected to porsol or polymer, so I guess we'll just let it be.

**Comment by andlaus** [comment]
the OPM github organization ( https://github.com/OPM ) gets a bit messy if abandoned repositories are kept. maybe we should add a second organization (e.g., OPM-archive?) and move such repositories there. That said, since modules that do not receive commits are listed at the bottom, I do not think that this is big issue.

**Pull request merged**
