### PR TITLE
Removing redundant checks from Nexus

### PR DESCRIPTION
**Pull request by alfbr**
Two checks were erroneously entered, based on a mix-up of which saturation to check. These are now removed. Simply run flow on the Norne deck to confirm.

### CODE REVIEW

**Comment by atgeirr** [comment]
> Simply run flow on the Norne deck to confirm.

I don't understand what that would confirm? Are these (wrong) checks among those triggered by the Norne deck?

**Comment by alfbr** [comment]
Yes, they are wrong checks. A run of Norne without this patch would yield:

Warning: For scaled endpoints input, cell(5, 10, 2) SATNUM = 1, SWCR > SOWCR

But this is based on a misread of the Nexus manual. It should be SWCR>(1-SOWCR) which is already covered by the check SOWCR+SWCR>=1.0.

Please note that the PR now also includes a tolerance. We have had false positives from, so errors now need to exceed 1e-6 to emit warning.

**Comment by atgeirr** [comment]
There are 27114 such warnings for Norne right now... If all of those are removed that is nice!

If there is no hurry I'll hold off merging things like this until Jenkins is fully functional. Otherwise, it looks benign enough.

**Comment by alfbr** [comment]
Sure, there is no hurry. Yes, many of them will go away :-)

**Comment by alfbr** [comment]
ping

**Comment by atgeirr** [comment]
jenkins build this with downstreams run norne please

**Comment by atgeirr** [comment]
All ok, merging.

**Pull request merged**
