### PR TITLE
Add operator== and operator!= to PhasePresence.

### PR DESCRIPTION
**Pull request by atgeirr**
This makes it simpler to write code debugging or inspecting changed phase configurations.

### CODE REVIEW

**Comment by jokva** [comment]
Minor, but they can be const'd

**Comment by atgeirr** [comment]
Will do, thanks for noticing.

**Comment by atgeirr** [comment]
Done.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Both CI systems return green.  I'll merge into master.  Thanks a lot!

**Pull request merged**
