### PR TITLE
Eclipsewriter: only write summary in substeps

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR fixes the issue of having "monstrous" amount of data produced when sub stepping is enabled. Now, only the summary is written on sub steps.

### CODE REVIEW

**Comment by bska** [comment]
Can you rebase this on top of current master to remove the merge commit (f28d0b6)?

**Comment by dr-robertk** [comment]
Rebased.

**Comment by bska** [comment]
> Rebased.

Thanks.  Unless anyone beats me to it, I'll test this once I'm done with #768.

**Comment by bska** [comment]
> I'll test this once I'm done with #768.

With the merging of #768 this can no longer be automatically merged due to relatively small conflicts being compounded by white-space adjustments through the introduction of the
```C++
 if( reportStepIdx_ != timer.reportStepNum() )
```
branch.

Would you mind rebasing this on top of current master?

**Comment by dr-robertk** [comment]
H, finally. I also took the liberty to fix a couple of minor issues introduced by the 768 PR.

**Comment by dr-robertk** [comment]
I just thought about it. I'm not sure what exactly was introduced by this RTF Handler. This is now only reported at report steps. In sub steps only the summary is written. Is this correct?

**Comment by bska** [comment]
> I'm not sure what exactly was introduced by this RTF Handler

It's entirely possible that I misunderstand the documentation, but as far as I can tell the keywords `WRFT` and `WRFTPLT` output data only at the (SCHEDULE) point at which the keyword is entered.  In other words, to have production logging output (pressures, saturations, flow rates &c) for the well bore throughout the simulation, one would need to specify the appropriate keyword (usually `WRFTPLT`) multiple times in the SCHEDULE section.

Maybe the authors @chflo, @joakim-hove, or @iLoop2 could weigh in on the matter?

**Comment by joakim-hove** [comment]
>It's entirely possible that I misunderstand the documentation, but as far as I can tell the keywords WRFT and WRFTPLT output data only at the (SCHEDULE) point at which the keyword is entered.

The `WRFT`and `WRFTPLT` keywords have quite rich behaviour, depending on the items chosen you can get:

- Output at the current timestep.
- Output for every timestep - starting now (or at a specified future timestep).
- Output at the current timestep - or alternatively when the well first opens.

All of the time related fencing is handled by the `EclipseState` object, and the RFT handler just consults a timeStep -> bool mapping to check whether an RFT should be output or not. 

>This is now only reported at report steps. In sub steps only the summary is written. Is this correct?

With a wide margin *good enough*. Depending on how you read the documentation it might be argued that RFT output should be generated for every simulator timestep when the second/third item of the `WRFTPLT` equals `TIMESTEP` - the underlying Parser++ functionality does not support that anyway.

**Comment by dr-robertk** [comment]
When running Norne now, I get the following output when writing a report step: 

PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data

Is this intended?

**Comment by chflo** [comment]
Yes, this is intended.  We do not support writing of PLT yet. Since PLT is a superset of RFT, we write RFT instead and write an error message.
In the near future, these messages will be written to a log instead.

**Comment by dr-robertk** [comment]
@chflo: good to know.

**Comment by dr-robertk** [comment]
@bska: I changed the default to std::invalid_argument.

**Comment by dr-robertk** [comment]
Ok, now it's "perfect". It would have been easier, just to provide the method in the first place.

**Comment by bska** [comment]
Thanks.  I'll merge into master.

**Pull request merged**
