### PR TITLE
Added small utility memcmp_double()

### PR DESCRIPTION
**Pull request by joakim-hove**
Very small utility for comparing two C double * vectors.

### CODE REVIEW

**Comment by atgeirr** [comment]
Looks fine, merging.

**Comment by bska** [comment]
According to the C standard we (users) are not allowed to introduce any symbols (i.e., functions) with external linkage whose names begin with `mem*`--at least if we're using a hosted implementation (which we are).  Those symbols are in the implementations's namespace to allow for future expansion of the standard.

**Comment by joakim-hove** [comment]
> According to the C standard we (users) are not allowed to introduce any symbols (i.e., functions) with external linkage whose names begin with mem*

Alriiight - that was certainly new to me; will come with an update tomorrow.

**Comment by atgeirr** [comment]
OK, let's rename it. I suggest `opm_memcmp_double`.

**Comment by bska** [comment]
>> According to the C standard we (users) are not allowed to introduce any symbols (i.e., functions) with external linkage whose names begin with `mem*`
>
> Alriiight - that was certainly new to me;

It's one of those details that escape notice for years.  The same holds for functions named `str*` and a few other names that I have to look up.

**Pull request merged**
