### PR TITLE
Fix saturation family diagnostics for two-phase case.

### PR DESCRIPTION
**Pull request by atgeirr**
Noticed while doing OPM/opm-simulators#878.

@qilicun can you verify this?

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by qilicun** [comment]
@atgeirr 

This Looks good. I will do some tests. Thanks.

**Comment by qilicun** [comment]
I confirm this works well with 2p case.

**Comment by atgeirr** [comment]
> I confirm this works well with 2p case.

I have checked Norne and SPE, so it should be mergable. I'd appreciate if you'd also carefully read the code to look for mistakes in the logic.

**Comment by qilicun** [comment]
>I have checked Norne and SPE, so it should be mergable. I'd appreciate if you'd also carefully read the code to look for mistakes in the logic.

I didn't find any mistakes in the logic... you can merge at your convenience。

**Pull request merged**
