### PR TITLE
Refactor relperm diagnostics using OpmLog functionalities.

### PR DESCRIPTION
**Pull request by qilicun**

### CODE REVIEW

**Comment by atgeirr** [comment]
This looks fine, just a few points:
 - will now all the warnings go to the PRT file (and there are lots for Norne for example), is this time consuming?
 - will we still get the summary count of errors and warnings after diagnostics? Will we get it again when the program is finished?

I assume one can answer these questions with a run of the Norne case, have you done that?

**Comment by qilicun** [comment]
>is this time consuming?

Currently, time consuming is not a problem, maybe later the log has much more functionality, for example ,output block pressure, that will be a time consuming issue, Alf suggest to consider multi-thread at that time.

>will we still get the summary count of errors and warnings after diagnostics? Will we get it again when the program is finished?

yes, that's ture, will fix this.

**Comment by akva2** [comment]
Can one of the admins verify this patch?

**Comment by atgeirr** [comment]
By verify, you mean?

**Comment by akva2** [comment]
sorry, i'll disable that. it's a jenkins auto-thingie.

**Comment by atgeirr** [comment]
What is it purpose and what triggers it?

**Comment by akva2** [comment]
whenever a non-whitelisted user opens a pull request, the github pull request builder auto-comments on them. i guess the idea is to attract the attention of admins. for some stupid reason it's on by default and i forgot to remove it when i installed the pr builder plugin on jenkins. i have now disabled it.

**Comment by atgeirr** [comment]
Looks like it was updated as requested, and a bug fixed as well. Thanks for your effort, will merge!

**Pull request merged**
