### PR TITLE
Using ppa for newer cmake version on travis.

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by atgeirr** [comment]
I assume this should be merged? @akva2 or @joakim-hove feel free to press the green button.

**Comment by atgeirr** [comment]
Rerunning travis, this failed. Not sure if it is worth to pursue further? @joakim-hove please weigh in.

**Comment by akva2** [comment]
afaict it's caused by using a backported compiler with a boost built with an older ABI.

**Comment by atgeirr** [comment]
> afaict it's caused by using a backported compiler with a boost built with an older ABI.

Sounds like a hornet's nest!

**Comment by akva2** [comment]
since travis has been shut down, i'll close this.

**Pull request closed without merging**
