### PR TITLE
changed: locate opm-cmake using config mode

### PR DESCRIPTION
**Pull request by akva2**
- requires https://github.com/OPM/opm-cmake/pull/12 for a fully working build.

### CODE REVIEW

**Comment by bska** [comment]
Do other modules need similar treatment or do they get the location of opm-cmake transitively from opm-core?

**Comment by akva2** [comment]
other modules need similiar treatment, i'll get to it as i go through the modules.

**Comment by bska** [comment]
> other modules need similar treatment

Right.  That's what I thought.

> i'll get to it as i go through the modules.

Thanks!

**Comment by akva2** [comment]
All pulls sent. With the referenced opm-cmake pull, this and the equivalents for the other modules,  builds on my box pass both as sibling and system installs.

**Comment by bska** [comment]
> @atgeirr merged commit 3f99037

Was this merged a tad too soon?  The introduction stipulates that this depends on OPM/opm-cmake#12 which is still not in opm-cmake's master branch.

**Comment by atgeirr** [comment]
Oops, I interpreted the comment "all pulls sent" as an all clear.

**Pull request merged**
