### PR TITLE
use standard filename for output log file.

### PR DESCRIPTION
**Pull request by qilicun**
If the deck file is **XXX.DATA**, output log file will be **XXX.LOG** in the same directory.

### CODE REVIEW

**Comment by atgeirr** [comment]
Seems reasonable, I just have one worry: should not the XXX.LOG filename be reserved for full simulator output log, so that we risk overwriting it with this diagnostic tool? What about XXX.RELPERMLOG?

**Comment by qilicun** [comment]
>so that we risk overwriting it with this diagnostic tool? 
That's true.

>What about XXX.RELPERMLOG?
But this is a standard-alone binary,  I can suppose that the user just use it for relperm diagnostics.

For the simulator output, it should be XXX.PRT I guess.

**Comment by alfbr** [comment]
Yes please, the output file should be named XXX.PRT. The log is basically the terminal output, while more exhaustive details are as expected in the PRT file. We want to overwrite the PRT file, this is the beginning of OPM's PRT and LOG files :-)

**Comment by alfbr** [comment]
My apologies, I mixed this pull request with the one for integrating the logging in flow. Since this is a stand-alone code, only intended for relperm diagnostics, I do agree with Atgeirr, we should name it accordingly. I suggest naming SATFUNCDIAGNOSIS.LOG. No strong opinions though, feel free to use another descriptive name of the log file.

For the PRT and LOG file in flow, my comments above apply though.

**Comment by qilicun** [comment]
@alfbr 

``the output file should be named XXX.PRT``

Yes, so that means ``.LOG`` file will not used by flow, we can keep this for relperm diagnostics. If it's so, @atgeirr will not worry that will be overwrite by flow. If you all agree, I think this PR should go in. :)

**Comment by atgeirr** [comment]
> Yes, so that means .LOG file will not used by flow, we can keep this for relperm diagnostics

I think this is wrong, that both .PRT and .LOG names should eventually be used by Flow, if I understood @alfbr correctly.

Therefore the file name used by this code should have a different ending (especially if you want to use the casename as base), for example .RELPERMLOG as I proposed earlier.

**Comment by alfbr** [comment]
I see, @atgeirr proposes to use the casename as prefix also for the relpermdiagnostics log-file, and extend the suffix to make it clear that the log-file is only from the relpermdiagnostics (and not flow). That makes sense I guess. I suggest using CASENAME.SATFUNCLOG instead though, capillary pressures and J-functions are quickly part of the diagnostics too. What do you think @qilicun ?

**Comment by qilicun** [comment]
I have no strong opinion on this, I think ``.SATFUNCLOG`` is a good name, will update this PR.

**Comment by atgeirr** [comment]
Thanks for updating, will merge!

**Pull request merged**
