### PR TITLE
Fix timestep bug

### PR DESCRIPTION
**Pull request by atgeirr**
The currentStepNum() method was used (wrongly) instead of reportStepNum() in the RFT-related parts of EclipseWriter and in EclipseWriteRFTHandler.

Also improved formatting in that part of the EclipseWriter (separate commit).

@joakim-hove I have assigned you to review/merge this.

### CODE REVIEW

**Comment by joakim-hove** [comment]
Well - I agree with this PR; however as I see it the underlying implementation of `SimtTimer` interface means that nothing is solved:

https://github.com/OPM/opm-core/blob/fbd6fce24f77dc7b999128409f51f6bda27f1926/opm/core/simulator/SimulatorTimerInterface.hpp#L50

**Comment by atgeirr** [comment]
> Well - I agree with this PR; however as I see it the underlying implementation of SimtTimer interface means that nothing is solved:

This is not a big problem for the current code, it is just a default implementation that will be overridden in subclasses if appropriate (and is overridden in the adaptive timer). However I agree that in general one should not provide default implementations in interface classes (and I'd be happy to see it gone here as well).

**Comment by joakim-hove** [comment]
> [ ... ]it is just a default implementation that will be overridden in subclasses if appropriate (and is overridden in the adaptive timer)

Well - to me it does not seem to be overridden in `flow`: https://github.com/OPM/opm-autodiff/blob/master/examples/flow.cpp#L405?

Feel free to ignore if I am misunderstanding here.

**Comment by atgeirr** [comment]
> Well - to me it does not seem to be overridden in flow: https://github.com/OPM/opm-autodiff/blob/master/examples/flow.cpp#L405?

It is true that the main() function deals with the regular timer (and for this timer step == report step). The adaptive timer is created and used inside the run() function of the Simulator class, and there one needs to separate the two concepts. However that is an implementation detail from the point of view of main().

**Pull request merged**
