### PR TITLE
Solver for the anisotropic Eikonal equation using fast marching method

### PR DESCRIPTION
**Pull request by atgeirr**
The anisotropic Eikonal equation is:
    grad(u)^T * M * grad(u) = 1
for some metric tensor M, that typically may vary in space.

This is currently used for making flow-diagnostic estimates of drained volume in the context of primary production, but could have numerous other uses.

The following limitations apply:
 - This is only a 2d code. While the general approach should work in 3d, there are nontrivial details that have not been worked out yet. The code tests for this.
 - The unit test is quite simple, and is a regression test rather than a truth test.
 - Performance is not very impressive, but good enough to be useful for testing the method.

### CODE REVIEW

**Comment by atgeirr** [comment]
Since no comments have been made, and also since this PR does not affect any existing code, I will merge this later today unless anyone objects.

**Comment by bska** [comment]
I tried to build this with GCC 4.4 and Boost 1.48 and got the following discouraging result:
```
opm-core/opm/core/tof/AnisotropicEikonal.hpp:25:41: error: boost/heap/fibonacci_heap.hpp: No such file or directory
opm-core/opm/core/tof/AnisotropicEikonal.hpp:57: error: ISO C++ forbids declaration of ‘set’ with no type
opm-core/opm/core/tof/AnisotropicEikonal.hpp:57: error: invalid use of ‘::’
opm-core/opm/core/tof/AnisotropicEikonal.hpp:57: error: expected ‘;’ before ‘<’ token
opm-core/opm/core/tof/AnisotropicEikonal.hpp:66: error: ‘boost::heap’ has not been declared
opm-core/opm/core/tof/AnisotropicEikonal.hpp:66: error: ISO C++ forbids declaration of ‘compare’ with no type
opm-core/opm/core/tof/AnisotropicEikonal.hpp:66: error: typedef name may not be a nested-name-specifier
opm-core/opm/core/tof/AnisotropicEikonal.hpp:66: error: expected ‘;’ before ‘<’ token
opm-core/opm/core/tof/AnisotropicEikonal.hpp:67: error: ‘boost::heap’ has not been declared
opm-core/opm/core/tof/AnisotropicEikonal.hpp:67: error: ISO C++ forbids declaration of ‘fibonacci_heap’ with no type
opm-core/opm/core/tof/AnisotropicEikonal.hpp:67: error: typedef name may not be a nested-name-specifier
opm-core/opm/core/tof/AnisotropicEikonal.hpp:67: error: expected ‘;’ before ‘<’ token
opm-core/opm/core/tof/AnisotropicEikonal.hpp:68: error: ‘Heap’ does not name a type
opm-core/opm/core/tof/AnisotropicEikonal.hpp:69: error: ‘Heap’ has not been declared
opm-core/opm/core/tof/AnisotropicEikonal.hpp:69: error: ISO C++ forbids declaration of ‘handle_type’ with no type
opm-core/opm/core/tof/AnisotropicEikonal.hpp:69: error: typedef name may not be a nested-name-specifier
opm-core/opm/core/tof/AnisotropicEikonal.hpp:69: error: expected ‘;’ before ‘HeapHandle’
opm-core/opm/core/tof/AnisotropicEikonal.hpp:70: error: ISO C++ forbids declaration of ‘map’ with no type
opm-core/opm/core/tof/AnisotropicEikonal.hpp:70: error: invalid use of ‘::’
opm-core/opm/core/tof/AnisotropicEikonal.hpp:70: error: expected ‘;’ before ‘<’ token
opm-core/opm/core/tof/AnisotropicEikonal.cpp:109: error: ‘accepted_front_’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:110: error: ‘considered_’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:111: error: ‘considered_handles_’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:148: error: unable to deduce ‘auto’ from ‘<expression error>’
opm-core/opm/core/tof/AnisotropicEikonal.cpp:167: error: unable to deduce ‘auto’ from ‘<expression error>’
opm-core/opm/core/tof/AnisotropicEikonal.cpp:224: error: ‘accepted_front_’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:233: error: ‘accepted_front_’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:261: error: ‘accepted_front_’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:270: error: ‘accepted_front_’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:360: error: ‘considered_’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:369: error: ‘HeapHandle’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:369: error: expected ‘;’ before ‘h’
opm-core/opm/core/tof/AnisotropicEikonal.cpp:370: error: ‘considered_handles_’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:370: error: ‘h’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:380: error: ‘considered_’ was not declared in this scope
opm-core/opm/core/tof/AnisotropicEikonal.cpp:381: error: ‘considered_handles_’ was not declared in this scope
```

**Comment by atgeirr** [comment]
Thanks for testing! The boost heap library seems to have been made available only in boost 1.49.0. According to opm-core-prereqs.cmake we currently require boost 1.44.

This blocks merging this PR as is. I see the following options (apart from dropping this and forgetting it):
 - Require boost 1.49.
 - Work around, by finding or making a replacement for the used Boost.Heap parts.
 - Putting the code in a separate branch on OPM/opm-core.

Apparently Ubuntu 12.04 includes 1.48. I assume that is the nail in the coffin for upping the required version for the time being, unless it turns out to be fairly easy (a command or two) to install 1.49 or newer. I guess ubuntu users would need newer versions of boost occasionally, but have not figured out how to do that myself. What is the boost version that is available on the RHEL systems?

**Comment by qilicun** [comment]
On RHEL for opm the boost version is 1.45.0  But I think it is easy to build a newer version for opm on RHEL, Alf maybe have the permission.

**Comment by alfbr** [comment]
We have already thrown in the towel for Red Hat, Boost is compiled manually, so upping to 1.49 is unproblematic. When it comes to Ubuntu 12.04 there are no official packages, but at least there is a ppa: https://launchpad.net/~boost-latest/+archive/ubuntu/ppa

Generally speaking boost is the one library we have said we would be flexible on when it comes to rolling out new versions, partly compensating for being conservative on the compiler.

**Comment by bska** [comment]
> I see the following options [...]:
> 
> * Require boost 1.49.
> * Work around, by finding or making a replacement for the used Boost.Heap parts.
> * Putting the code in a separate branch on OPM/opm-core.

Only enable Eikonal solves if Boost 1.49 or later is available?

**Comment by atgeirr** [comment]
@bska's solutions seems to me to be the simplest. I will revise the proposal using boost/version.hpp.

**Comment by bska** [comment]
> I will revise the proposal using `boost/version.hpp`.

We could also consider a CMake-based approach.

**Comment by atgeirr** [comment]
An approach with conditional compilation would be a little cleaner, but my cmake skills are not quite there. I have implemented a simple fix using the boost version.hpp header, that throws with an informative error message if you built with too old boost version to use the class. I hope that is acceptable for now. When we at some point require newer boost versions, we can remove the ugly conditionals.

**Comment by bska** [comment]
> I have implemented a simple fix using the boost `version.hpp` header,

Right.  You probably need similar treatment in the unit test though.

**Comment by atgeirr** [comment]
I have addressed the issues, with the error message and the unit test. Using a build-system conditional looks like a better medium-term solution now that I see the amount of messiness with the #if statements, but hopefully this is good enough in the short term (long term we will require new enough boost version).

**Comment by bska** [comment]
> I have addressed the issues, with the error message and the unit test.

Thanks.  I'll kick off a test build.

**Comment by bska** [comment]
No further issues.  Builds and all tests run.  I'll merge into master.  Thanks a lot.

**Pull request merged**
