### PR TITLE
Update CMake list with deleted files, and delete files moved to opm-simulators.

### PR DESCRIPTION
**Pull request by atgeirr**
This removes the files that have been moved to opm-simulators.

This requires OPM/opm-simulators#646 (otherwise includes will fail).

### CODE REVIEW

**Comment by bska** [comment]
Please rebase onto current OPM master.

**Comment by atgeirr** [comment]
This has been rebased and the downstream PR updated.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> This has been rebased and the downstream PR updated.

Thanks.  I'll merge into master.

**Pull request merged**
