### PR TITLE
Add solvent to solution vector if present

### PR DESCRIPTION
**Pull request by totto82**
Also move BlackoilSolventState from opm-simulators to opm-core.

### CODE REVIEW

**Comment by atgeirr** [comment]
Actually I'd rather move the other state classes in the opposite direction. Any particular reason not to?

**Comment by totto82** [comment]
They are needed in opm-output.

**Comment by atgeirr** [comment]
> They are needed in opm-output

This cannot be right, as opm-output does not depend on opm-core (it's the other way around).

**Comment by totto82** [comment]
You are right. They are not needed in output, but in Compat.hpp (in opm-core). Is it safe to move Compat.hpp to opm-simulators? As fare as I see it is only used in  SimulatorFullyImplicitBlackoilOutput.cpp.

**Comment by atgeirr** [comment]
I think that should be safe to do, yes.

**Comment by jokva** [comment]
It would be even better if you could kill off Compat.hpp.

**Comment by totto82** [comment]
This PR is supersede by #1071

**Pull request closed without merging**
