### PR TITLE
remove AdaptiveTimeStepping class

### PR DESCRIPTION
**Pull request by akva2**
has been moved to opm-simulators. ref https://github.com/OPM/opm-simulators/pull/1049

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams opm-simulators=1049 please

**Comment by akva2** [comment]
jenkins build this with downstreams opm-simulators=1049 please

**Comment by akva2** [comment]
there. removed WIP label, but i guess it may still be a bit WIP in the sense that there could be more files to move

**Comment by atgeirr** [comment]
I count 13 files added to the other repo, both as files and in the cmake list. In this PR I count 13 files removed in the cmake list, but only 10 files actually removed. Either a few more files should be deleted, or I have lost my ability to count...

**Comment by akva2** [comment]
nicely spotted. forgot to push last version of this branch.

**Comment by atgeirr** [comment]
Thanks for fixing, I'll merge!

**Pull request merged**
