### PR TITLE
Implement solvent model in flow_ebos

### PR DESCRIPTION
**Pull request by totto82**
1) Add has_solvent to phase_usage 
2) Add solvent saturation to BlackoilState

### CODE REVIEW

**Comment by totto82** [comment]
Anybody now why test 30 keeps failing for all new PRs. 
30 - compareECLInitFiles_flow_ebos+NORNE_ATW2013 (Failed)

**Comment by atgeirr** [comment]
See OPM/opm-data#210. Should be fixed soonish.

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by totto82** [comment]
The OPM/opm-simulators#1178 should fix the test failure and they should be merged together.

**Comment by andlaus** [comment]
I guess you don't need the changes to `PhaseUsage` anymore?

**Pull request merged**
