### PR TITLE
Fix type bug in equil

### PR DESCRIPTION
**Pull request by atgeirr**
This is a simple fix, but it does change the values produced, and should be tested with model 2 etc. before merging.

### CODE REVIEW

**Comment by bska** [comment]
> This is a simple fix,

I distinctly remember making a note of this issue some time ago, but now I can't find my notes anywhere.  I'll launch a Jenkins run and defer other testing to others.

**Comment by bska** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
It turns out that this bugfix causes test failures in opm-simulators. Probably minor changes to initial values cascade to cause larger differences. That must be investigated and fixed before merging this. It is likely that all regression test bases must be updated.

The opm-simulators tests that fail are:
```
19/26 Test #19: compareECLFiles_flow+SPE3CASE1 .................***Failed    2.47 sec
20/26 Test #20: compareECLFiles_flow+SPE9_CP_SHORT .............***Failed   16.15 sec
```

**Comment by atgeirr** [comment]
I'll resurrect this small fix to get it out of the way before we reorganize (kill...) opm-core.

**Comment by andlaus** [comment]
@atgeirr what's the status here? since the current code in master is obviously wrong, is there a chance to get this merged in time for the release?

**Comment by atgeirr** [comment]
I hope so. The annoying part here is updating the tests. I'll have to wait until #1179 is in though (otherwise that PR must be redone).

**Comment by atgeirr** [comment]
jenkins build this with downstreams run norne please

**Comment by atgeirr** [comment]
This simple bugfix changes the initial state and therefore all simulation results. Tests fail in opm-simulators, but results are hopefully better and more correct! For other testcases I would appreciate some help in testing. In particular, @alfbr or @totto82, could one of you test this PR with model 2 (new realizations)?

**Comment by atgeirr** [comment]
As expected, Jenkins failed on 10 testcases. Luckily they are the same 10 cases that fail for me locally, so I can inspect and (hopefully) verify that the new solutions are good.

**Comment by atgeirr** [comment]
Having investigated the failing cases, these are my findings:
```
         26 - compareECLFiles_flow+SPE3CASE1 (Failed)
	 27 - compareECLFiles_flow_ebos+SPE3CASE1 (Failed)
         36 - compareECLFiles_flow_solvent+SPE5CASE1 (Failed)
```

For all of these cases, there were differences in timestepping that cause test failures. For SPE3CASE1 it is similar to before: the first step may or may not be chopped (with this PR it is chopped again unless re-coarsening tolerance_wells again). For SPE5CASE1 it looks to me like it currently chops the first step on master, but does not with this PR.

```
         29 - compareECLFiles_flow+SPE9_CP_SHORT (Failed)
	 30 - compareECLFiles_flow_ebos+SPE9_CP_SHORT (Failed)
	 31 - compareECLFiles_flow_legacy+SPE9_CP_SHORT (Failed)
         32 - compareECLFiles_flow+SPE9_CP_GROUP (Failed)
	 33 - compareECLFiles_flow_ebos+SPE9_CP_GROUP (Failed)
         35 - compareECLFiles_flow_polymer+2D_THREEPHASE_POLY_HETER (Failed)
```
The maximum relative differences across all of these cases are 1.3e-3. Most flagged relative differences are just above 1e-5. I think for these tests just generating new references with update_data is ok.

```
         34 - compareECLFiles_flow_multisegment+2D_H__ (Failed)
```

Here there are no timestep differences, but still somewhat large difference for RS (only). An excerpt from the test:

```
34: Comparing RS...
34: Occurrence in first file    = 78
34: Occurrence in second file   = 78
34: Grid coordinate             = (17, 1, 5)
34: (first value, second value) = (126.323, 124.011)
34: 
34: Program threw an exception: [/Users/atgeirr/opm-build-release/opm-output/opm/test_util/EclFilesComparator.cpp:370] Deviations exceed tolerances.
34: The absolute deviation is 2.31239, and the tolerance limit is 0.02.
34: The relative deviation is 0.0183053, and the tolerance limit is 1e-05.
```

So: before we can merge this we must investigate test 34 results a little to see if new behaviour is ok (also, that test will be somewhat obsolete soon as we merge the new mswells). Also we must find a set of parameters that give uniform first-step behaviour (chopping or not) for SPE3 and SPE5.

**Comment by alfbr** [comment]
Ah, this one slip through the cracks, sorry for not checking. Thanks for the thorough walk through! Please let me know if you still need me to help out assessing the differences.

**Comment by atgeirr** [comment]
> Please let me know if you still need me to help out assessing the differences.

Yes, if you could test this with a model 2 realization or two that would be good! For the testcases I think I'll figure it out by myself.

**Comment by alfbr** [comment]
I will try to get it done Monday.

**Comment by totto82** [comment]
Since this may effect my recent  work on issues related to swatinit and pc scaling I want to test this as well. Currently testing on rel 0.

**Comment by atgeirr** [comment]
> Since this may effect my recent work on issues related to swatinit and pc scaling I want to test this as well. Currently testing on rel 0.

Great! It's an obvious bug with a trivial fix, yet the consequences of changing initial values even slightly are hard to predict.

**Comment by alfbr** [comment]
> Since this may effect my recent work on issues related to swatinit and pc scaling I want to test this as well. Currently testing on rel 0.

Thanks! Please also check for correctness while you have the results open, it will let me off the hook.

**Comment by totto82** [comment]
The water production results on rel 0 are improved with this PR. I can send you some results by email.

**Comment by alfbr** [comment]
Cool, thanks!

**Comment by totto82** [comment]
There seem to be some unwanted effects of this PR in terms of convergence that needs more investigations. I suggest not merging this now, but after the release.

**Comment by atgeirr** [comment]
> I suggest not merging this now, but after the release.

Ok, then we'll have a bit more breathing room to investigate.

**Comment by atgeirr** [comment]
So @totto82 I hope we can restart the effort to get this in again? If so, what were the effects you saw on convergence? Since this is only changing initial values, any worse convergence is just bad luck, and could hopefully we fixed with a little tuning?

**Comment by totto82** [comment]
I am sure it was just random noise. But I could actually see very small changes in one on the well curves after a period of convergence issues. I can re-run the tests and give you some more details. But I would like to wait until the wellModel PR is merged and the soon coming PR where adding the schur complement of the well eq is moved after the convergence check.  This is a clear bug and may also effect how we analyze this PR.

**Comment by totto82** [comment]
The change in solution happens when the linear solver fails in the first step. The fix in OPM/opm-simulators#1322 should fix this. I will test this again when OPM/opm-simulators#1322 is merged.

**Comment by atgeirr** [comment]
Rerunning Jenkins after merging the fix mentioned above.

**Comment by atgeirr** [comment]
jenkins build this with downstreams run norne please

**Comment by totto82** [comment]
This PR still changes convergence behavior 
Number of problems goes from 17 -> 22 for rel 0 and 157->202 for rel 5.
which gives a slowdown of almost 10% for rel 5. 
The rel 0 results are good, but there is some discrepancies for rel5, where the results on some wells are improved and some are not.

**Comment by atgeirr** [comment]
> This PR still changes convergence behavior
> Number of problems goes from 17 -> 22 for rel 0 and 157->202 for rel 5.
> which gives a slowdown of almost 10% for rel 5.
> The rel 0 results are good, but there is some discrepancies for rel5, where the results on some wells are improved and some are not.

That is very annoying... Especially since this is such a small and obviously correct change! Perhaps it is just bringing other problems out into the light?

**Comment by atgeirr** [comment]
jenkins build this with downstreams update_data please

**Comment by atgeirr** [comment]
jenkins build this with downstreams update_data please

**Comment by atgeirr** [comment]
The Jenkins failures (and a little diagnosis) are:
```
mpi.compareECLFiles_flow+2D_H__
 (large difference in RS, but in a cell with SWAT==1)
mpi.compareECLFiles_flow+SPE5CASE1
mpi.compareECLFiles_flow+SPE3CASE1
 (chop first step or not)
mpi.compareECLFiles_flow+3D_MSW
mpi.compareECLFiles_flow+SPE9_CP_SHORT
mpi.compareECLFiles_flow_legacy+SPE9_CP_SHORT
mpi.compareECLFiles_flow+SPE9_CP_GROUP
 (changes of magnitude max 7e-4, ok to update)
```

**Comment by atgeirr** [comment]
jenkins build this with downstreams opm-data=275 please

**Comment by atgeirr** [comment]
Ok, then this goes in, in spite of some failed tests locally for me (I'll not let that hold up everything else, but might suggest some changes later motivated by restoring them).

**Pull request merged**
