### PR TITLE
Remove unused program

### PR DESCRIPTION
**Pull request by atgeirr**
Another small cleanup step.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this with downstreams

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
> please

I usually remember to ask Jenkins nicely...

**Comment by andlaus** [comment]
always keep your stiff upper lip when talking to your buttler ;)

**Comment by atgeirr** [comment]
Will self-merge as no-one will be affected.

**Pull request merged**
