### PR TITLE
Make WellsManager compile with c++-11.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR replaces the initializer list on the constructor of WellsManager with the equally valid empty construction of objects. Otherwise the code won't compile without the c++14 flag which is not needed anywhere else.

### CODE REVIEW

**Comment by atgeirr** [comment]
The Travis failure is due to this:
```
/home/travis/build/OPM/opm-simulators/opm/autodiff/FlowMain.hpp:432:106: error: could not convert ‘{{Opm::Log::MessageType::Note, <expression error>}, {Opm::Log::MessageType::Info, <expression error>}, {Opm::Log::MessageType::Warning, <expression error>}, {Opm::Log::MessageType::Error, <expression error>}, {Opm::Log::MessageType::Problem, <expression error>}, {Opm::Log::MessageType::Bug, <expression error>}}’ from ‘<brace-enclosed initializer list>’ to ‘const std::map<long int, int>’
                                                    {Log::MessageType::Bug, msgLimits.getBugPrintLimit(0)}};
```

Will look into it. Could it be a similar kind of error to the one you are fixing here?

**Comment by dr-robertk** [comment]
Yeah. Seems like it. For some reasons the c++-14 did not get activated for my configuration. But I guess c++-11 should be good enough. The rest compiles though.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Jenkins is green, Jenkins is green, merging.

**Pull request merged**
