### PR TITLE
Update the swatinit test base on fix in opm-material#248

### PR DESCRIPTION
**Pull request by totto82**
Depends on OPM/opm-material#248

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-material#248 please

**Comment by totto82** [comment]
jenkins build this opm-material=248 please

**Comment by atgeirr** [comment]
jenkins build this opm-material=248 with downstreams please

**Comment by atgeirr** [comment]
Everything ok here, merging this and upstream PR.

**Pull request merged**
