### PR TITLE
Fix test equil

### PR DESCRIPTION
**Pull request by totto82**
This should fix the test. 
See issue #1148 
This PR also undo #1149

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this with downstreams please

**Comment by bska** [comment]
Just out of interest: How did you derive the new expected values?

**Comment by totto82** [comment]
I have verified the values against Eclipse. They are within a few %. But I used values generated by opm in order to use a stricter tolerance for the test.

**Comment by atgeirr** [comment]
Jenkins is ok, local test is ok, and it only affects a test in opm-core, so I'll merge. Thanks for reinstating the test!

**Pull request merged**
