### PR TITLE
[cmake] Add CMake module for finding PT-Scotch in dune-cornerpoint

### PR DESCRIPTION
**Pull request by blattms**
There already is a module for finding Zoltan, which supports
both ParMETIS and PT-Scotch underneath. While the former is
only free for academic use the latter is true open source. Therefore
with this commit we add a module for finding PT-Scotch and add the
necessary libraries and include paths for ZOLTAN.

This PR will be needed for the new load balancing in dune-cornerpoint.

### CODE REVIEW

**Comment by blattms** [comment]
Should I propagate this PR to the other modules, too? To all of them or just the ones that use dune-cornerpoint? Is there a script?

**Comment by blattms** [comment]
Is @rolk's description at https://github.com/rolk/rolk.github.io/blob/master/_posts/2013-09-23-build-system-sync.md still up to date?

**Comment by bska** [comment]
I'll take care of propagating the module to the other repositories (including opm-cmake).

**Comment by blattms** [comment]
@bsak Great! Thanks a lot.

**Comment by atgeirr** [comment]
I do not think this has been incorporated in any way, and since the build-system no longer resides in opm-core but in opm-cmake I will close the issue, and must ask you to open a new PR in opm-cmake. Sorry for the inconvenience. At least the "propagate build system changes" part is no longer needed!

**Pull request closed without merging**
