### PR TITLE
Fix abs bug and warnings

### PR DESCRIPTION
**Pull request by joakim-hove**
This PR should **not** be merged - it is only a convenient demonstration.

### CODE REVIEW

**Comment by atgeirr** [comment]
Is it because it makes the memcmp function public you don't want it merged? Because it is better to have tests for it than not.

**Comment by joakim-hove** [comment]
> Is it because it makes the memcmp function public you don't want it merged?

Well yes; so before someone hit me in the head with a clue-stick I was very upfront about not merging. But yes - I agree that having a test is always better than not having one; I could move it to e.g `opm/core/utility/memcmp_double.h`?

**Comment by atgeirr** [comment]
Sounds good to me!

**Comment by joakim-hove** [comment]
OK - micro PR here: https://github.com/OPM/opm-core/pull/849

**Pull request closed without merging**
