### PR TITLE
Remove more files moved to opm-grid.

### PR DESCRIPTION
**Pull request by atgeirr**
This should complete the grid code relocation.

Only tiny remnant is test_pinchprocessor.cpp, but that one requires transmissibility calculations that are still located here, so it remains for now.

### CODE REVIEW

**Comment by atgeirr** [comment]
Requires OPM/opm-grid#258.

**Comment by bska** [comment]
jenkins build this with downstreams opm-grid=258 please

**Comment by bska** [comment]
jenkins build this with downstreams opm-grid=258 please

**Comment by dr-robertk** [comment]
It tested the module chain with both PRs and it worked fine.

**Comment by atgeirr** [comment]
Thanks for testing, I'll merge now.

**Pull request merged**
